bitcoinNetwork: bsv

logLevel: Debug

logFileName: ./debug.log

endPointHTTPSListenIP: 127.0.0.1

endPointHTTPSListenPort: 9091

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

tlsCertificatePath : ./example.crt

tlsKeyfilePath : ./example.key

tlsCertificateStorePath : ./

defaultSathosi: 199

xokenListenIP: 127.0.0.1

xokenListenPort: 9090
