bitcoinNetwork: bsv

logLevel: Debug

logFileName: ./debug.log

endPointHTTPSListenIP: 127.0.0.1

endPointHTTPSListenPort: 9091

encryptedSeed: 7Bq7Ls8oz0seH7AzwrsuqiS1UEgBHG1GOG0yK6xUsjEiil9drMLdWOnwEf4lfus+4UED60wU5fha7QjemUhMYw==

tlsCertificatePath : ./example.crt

tlsKeyfilePath : ./example.key

tlsCertificateStorePath : ./

defaultSathosi: 199

xokenListenIP: 127.0.0.1

xokenListenPort: 9090
